### PR TITLE
feat(frontend): fix-footer-logo-dark-theme

### LINKED ISSUE #220: Fix footer logo in dark theme
Captura de pantalla (435)

### PR DESCRIPTION
**Pull request by leisterfrancisco**
### GH Issue

Resolves #220  

### Steps to test
1. Check footer logo in dark mode is visible

#### CheckList
- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

### CODE REVIEW

**Review by AngeloCG97 — DISMISSED** [review]

File: src/theme/Footer/index.js [hunk 1]
```diff
@@ -40,18 +41,23 @@ const FooterLogo = ({url, alt}) => (
...
 function Footer() {
+  const {isDarkTheme} = useThemeContext();
   const context = useDocusaurusContext();
   const {siteConfig = {}} = context;
   const {themeConfig = {}} = siteConfig;
   const {footer} = themeConfig;
 
   const {copyright, links = [], logo = {}} = footer || {};
-  const logoUrl = useBaseUrl(logo.src);
+  var logoUrl = useBaseUrl(logo.src);
```
Comment (AngeloCG97) [inline src/theme/Footer/index.js:51]: use const please

Comment (leisterfrancisco) [reply src/theme/Footer/index.js]: Thank you for your observation

**Review by AngeloCG97 — APPROVED** [review]

**Review by xavier506 — APPROVED** [review]
Nice work!
